# Generated by Django 4.2.1 on 2023-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTIAPP', '0002_remove_comment_user_mbti_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
