# Generated by Django 4.2.1 on 2023-06-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBTIAPP', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catego',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='MBTIAPP.category'),
            preserve_default=False,
        ),
    ]
